# Node.js with React
# Build a Node.js project that uses Reactttt.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop

stages:
  - stage: Despliegue
    jobs:
      - job: BuildAndDeploy
        displayName: 'Build and Deploy Job'
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Instalar Node.js'

          - script: npm cache clean --force
            displayName: 'Limpiar cach√© de npm'

          - script: |
              cd Sgart_front
              npm install
            displayName: 'Instalar dependencias'

          - script: |
              cd Sgart_front
              npm run build
            displayName: 'Build'

          - script: |
              npm install -g firebase-tools
              firebase deploy --token $(FIREBASE_TOKEN)
            displayName: 'Despliegue'

  - stage: SonarQube
    jobs:
      - job: SonarQubeJob
        displayName: 'SonarQube Analysis Job'
        pool:
          name: Default
          demands:
            - agent.name -equals SonarLocalPC
        steps:
          - checkout: none
          - script: |
              sonar-scanner \
              -Dsonar.token=$(SQ_TOKEN) \
              -Dproject.settings=sgart.backend/sonar-project.properties \
              -Dsonar.coverage.jacoco.xmlReportPaths=sgart.backend/target/site/jacoco/jacoco.xml
            displayName: 'SonarQube analysis'
          - script: echo "SonarQube OK"
            displayName: 'Confirm SonarQube'
